//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\TSO.mdf;Integ" +
            "rated Security=True")]
        public string TSOConnectionString {
            get {
                return ((string)(this["TSOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=\"D:\\ТЕХНИКУМ\\3 КУРС\\2 СЕМЕСТР\\" +
            "ПРОИЗВОДСТВЕННАЯ ПРАКТИКА\\ПРАКТИКА\\TSO.MDF\";Integrated Security=True;Connect Tim" +
            "eout=30;Encrypt=False;TrustServerCertificate=False")]
        public string D__ТЕХНИКУМ_3_КУРС_2_СЕМЕСТР_ПРОИЗВОДСТВЕННАЯ_ПРАКТИКА_ПРАКТИКА_TSO_MDFConnectionString {
            get {
                return ((string)(this["D__ТЕХНИКУМ_3_КУРС_2_СЕМЕСТР_ПРОИЗВОДСТВЕННАЯ_ПРАКТИКА_ПРАКТИКА_TSO_MDFConnection" +
                    "String"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\TSO_DB.mdf;In" +
            "tegrated Security=True;Connect Timeout=30")]
        public string TSO_DBConnectionString {
            get {
                return ((string)(this["TSO_DBConnectionString"]));
            }
        }
    }
}
